Abraham
Team-17-Bedu/r-postworks pull request #2
Opened 2021-01-21 05:47 UTC by Aabraham-Farias

Postwork 1 y dos

2021-01-21 16:15 UTC, begeistert commented on src/2dopostwork/2doPostwork.R
> +#fijamos directorio
Creo que el comentario correcto debería ser

```r
# Fijamos el directorio de trabajo
```

2021-01-21 16:18 UTC, begeistert commented on src/2dopostwork/2doPostwork.R
> +#descargamos los datasets
Considero que el lenguaje debería ser mas formal y dejando todo en tercera persona, por ejemplo, en lugar de 

```r
#descargamos los datasets
```
Algo más formal podría ser 
```r
# Descarga de los datasets
```

2021-01-21 16:22 UTC, begeistert commented on src/2dopostwork/2doPostwork.R
> +#leer los archivos descargados con el comando lapply
En Python existe una norma o documento que determina incluso como se escribirán los comentarios, esta es llamada `PEP`, a lo que quiero llegar es que los comentarios deberían comenzar con mayúscula y con un espacio después del hashtag, por ejemplo
```r
# Lectura de los ficheros descargados con el comando lapply
```

Recuerda que solo son comentarios, puedes pasarlos por alto si los demás están de acuerdo con que este así

2021-01-21 16:25 UTC, begeistert requested changes
Desde mi punto de vista, únicamente mejoraría los comentarios, ya que deberían verse mejor y estar mejor redactados, si Raul esta en desacuerdo con mis comentarios cambiaré mi review.

2021-01-24 20:08 UTC, alevs97 approved these changes

2021-01-31 00:00 UTC, begeistert approved these changes

2021-01-31 00:01 UTC, merged